/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#fef9ef',
        'on-background': '#1d1c16',
        'on-surface': '#1d1c16',
        'surface-bright': '#fef9ef',
        'surface-dim': '#dedad0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f3e9',
        'surface-container': '#f2ede3',
        'surface-container-high': '#ede3cf',
        'surface-container-highest': '#e7e2d8',
        'outline': '#797587',
        'outline-variant': '#c9c4d8',
        'primary': '#5d39e0',
        'on-primary': '#ffffff',
        'primary-fixed': '#e6deff',
        'primary-fixed-dim': '#cabeff',
        'on-primary-fixed': '#1c0062',
        'on-primary-fixed-variant': '#4716cb',
        'secondary': '#b12e09',
        'secondary-container': '#fd643d',
        'on-secondary-container': '#5e1100',
        'secondary-fixed-dim': '#ffb4a2',
        'on-secondary-fixed': '#5e1100',
        'tertiary-fixed': '#f3e48f',
        'on-tertiary-fixed': '#201c00',
        'on-tertiary-fixed-variant': '#514700',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#f5f0e6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body: ['"Noto Serif"', 'Georgia', 'serif'],
        label: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      maxWidth: {
        prose: '42rem',
      },
    },
  },
  plugins: [],
};
